# Generated by Django 4.2 on 2023-04-24 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0004_profissao_alter_cliente_cpf_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name_plural': 'profissões'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroCliente.profissao'),
        ),
    ]
