# Generated by Django 4.2 on 2023-04-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0005_alter_profissao_options_cliente_profissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissao',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
