# Generated by Django 4.2 on 2023-04-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0008_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='interesses',
            field=models.ManyToManyField(to='CadastroCliente.interesse'),
        ),
    ]
